stages:
- lint
- build
- build-review
- review
- release
- deploy

variables:
  REPO: "dbogatov/my-cv"

include:
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/latex-report/chktex.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/latex-report/cspell.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/latex-report/build.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/latex-report/artifacts.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/latex-review-apps/build-review.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/latex-review-apps/review.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/latex-review-apps/stop-review.yml'

deploy:
  image: dbogatov/docker-images:alpine-extras-latest
  stage: deploy
  variables:
    GIT_STRATEGY: none
  dependencies: []
  script:
  - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://git.dbogatov.org/api/v4/projects/13/trigger/pipeline
  tags:
  - docker
  only:
  - master
